version: '3'
services:
    db-migration:
        build: .
        command: npm run migrate:latest
        volumes:
            - .:/app/
        depends_on:
            - postgres
        env_file:
            - '.env'
        environment:
            DATABASE_URL: postgres://fish-bot-user:fish-bot-pwd@postgres:5432/fish-bot
    db-migration-rollback:
        build: .
        command: npm run migrate:rollback
        volumes:
            - .:/app/
        depends_on:
            - postgres
        env_file:
            - '.env'
        environment:
            DATABASE_URL: postgres://fish-bot-user:fish-bot-pwd@postgres:5432/fish-bot
    app:
        build: .
        command: npm run dev
        volumes:
            - .:/app/
        ports:
            - '3000:3000'
        depends_on:
            - postgres
            - redis
        env_file:
            - '.env'
        environment:
            DATABASE_URL: postgres://fish-bot-user:fish-bot-pwd@postgres:5432/fish-bot
            REDIS_URL: redis://redis:6379
    postgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_DB: fish-bot
            POSTGRES_USER: fish-bot-user
            POSTGRES_PASSWORD: fish-bot-pwd
        ports:
            - '5432:5432'
        volumes:
            - data:/var/lib/postgresql/data/
    redis:
        image: redis
        expose: 
            - 6379
volumes:
    data: {}
