version: '3'
services:
    app:
        build: .
        command: npm run dev
        volumes:
            - app:/app
            - nodemodules:/app/node_modules
        ports:
            - '3000:3000'
        depends_on:
            - postgres
        env_file:
            - '.env'
        environment:
            DATABASE_URL: postgres://fish-bot-user:fish-bot-pwd@postgres:5432/fish-bot
    postgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_DB: fish-bot
            POSTGRES_USER: fish-bot-user
            POSTGRES_PASSWORD: fish-bot-pwd
        ports:
            - '5432:5432'
        volumes:
            - data:/var/lib/postgresql/data/
volumes:
    data: {}
    app: {}
    nodemodules: {}
