import { Worlds } from './extract-character';

export type WorldToRegion = {
    [k in Worlds]: 'na' | 'eu' | 'oc' | 'jp';
};

export const worldToRegion: WorldToRegion = {
    [Worlds.Adamantoise]: 'na',
    [Worlds.Cactuar]: 'na',
    [Worlds.Faerie]: 'na',
    [Worlds.Gilgamesh]: 'na',
    [Worlds.Jenova]: 'na',
    [Worlds.Midgardsormr]: 'na',
    [Worlds.Sargatanas]: 'na',
    [Worlds.Siren]: 'na',
    [Worlds.Balmung]: 'na',
    [Worlds.Brynhildr]: 'na',
    [Worlds.Coeurl]: 'na',
    [Worlds.Diabolos]: 'na',
    [Worlds.Goblin]: 'na',
    [Worlds.Malboro]: 'na',
    [Worlds.Mateus]: 'na',
    [Worlds.Zalera]: 'na',
    [Worlds.Behemoth]: 'na',
    [Worlds.Excalibur]: 'na',
    [Worlds.Exodus]: 'na',
    [Worlds.Famfrit]: 'na',
    [Worlds.Hyperion]: 'na',
    [Worlds.Lamia]: 'na',
    [Worlds.Leviathan]: 'na',
    [Worlds.Ultros]: 'na',
    [Worlds.Cerberus]: 'eu',
    [Worlds.Louisoix]: 'eu',
    [Worlds.Moogle]: 'eu',
    [Worlds.Omega]: 'eu',
    [Worlds.Phantom]: 'eu',
    [Worlds.Ragnarok]: 'eu',
    [Worlds.Sagittarius]: 'eu',
    [Worlds.Spriggan]: 'eu',
    [Worlds.Alpha]: 'eu',
    [Worlds.Lich]: 'eu',
    [Worlds.Odin]: 'eu',
    [Worlds.Phoenix]: 'eu',
    [Worlds.Raiden]: 'eu',
    [Worlds.Shiva]: 'eu',
    [Worlds.Twintania]: 'eu',
    [Worlds.Zodiark]: 'eu',
    [Worlds.Bismarck]: 'oc',
    [Worlds.Ravana]: 'oc',
    [Worlds.Sephirot]: 'oc',
    [Worlds.Sophia]: 'oc',
    [Worlds.Zurvan]: 'oc',
    [Worlds.Aegis]: 'jp',
    [Worlds.Atomos]: 'jp',
    [Worlds.Carbuncle]: 'jp',
    [Worlds.Garuda]: 'jp',
    [Worlds.Gungnir]: 'jp',
    [Worlds.Kujata]: 'jp',
    [Worlds.Tonberry]: 'jp',
    [Worlds.Typhon]: 'jp',
    [Worlds.Alexander]: 'jp',
    [Worlds.Bahamut]: 'jp',
    [Worlds.Durandal]: 'jp',
    [Worlds.Fenrir]: 'jp',
    [Worlds.Ifrit]: 'jp',
    [Worlds.Ridill]: 'jp',
    [Worlds.Tiamat]: 'jp',
    [Worlds.Ultima]: 'jp',
    [Worlds.Anima]: 'jp',
    [Worlds.Asura]: 'jp',
    [Worlds.Chocobo]: 'jp',
    [Worlds.Hades]: 'jp',
    [Worlds.Ixion]: 'jp',
    [Worlds.Masamune]: 'jp',
    [Worlds.Pandaemonium]: 'jp',
    [Worlds.Titan]: 'jp',
    [Worlds.Belias]: 'jp',
    [Worlds.Mandragora]: 'jp',
    [Worlds.Ramuh]: 'jp',
    [Worlds.Shinryu]: 'jp',
    [Worlds.Unicorn]: 'jp',
    [Worlds.Valefor]: 'jp',
    [Worlds.Yojimbo]: 'jp',
    [Worlds.Zeromus]: 'jp',
};
