export const APPLICATION_ID = process.env.DISCORD_APPLICATION_ID || '';
export const DATABASE_URL = process.env.DATABASE_URL;
export const PORT = process.env.PORT;
export const ENVIRONMENT = process.env.ENVIRONMENT || 'development';
export const DISCORD_PUBLIC_KEY = process.env.DISCORD_PUBLIC_KEY || '';
export const DISCORD_APPLICATION_ID = process.env.DISCORD_APPLICATION_ID;
export const DISCORD_TOKEN = process.env.DISCORD_TOKEN;
export const FFLOGS_CLIENT_ID = process.env.FFLOGS_CLIENT_ID;
export const FFLOGS_CLIENT_SECRET = process.env.FFLOGS_CLIENT_SECRET;
